### ISSUE TITLE
can not use for loop

### ISSUE THREAD

**Issue by stansu** [DeclanRussell/NvidiaAIDenoiser#11]
After I launch exe and finished denoise, the command-line window won't close, so for loop don't work.

**Comment by DeclanRussell** [comment]
Hey @stansu,
Can you give some more context about hoe you are launching the exe? Are you using some kind of batch/python script?

**Comment by stansu** [comment]
I'm using the batch file example you provided. When it finished, it show 'done!'.

**Comment by jackyjacky1307** [comment]
I have the same problem when I using win7, but it's woking when I use win10.

**Comment by DeclanRussell** [comment]
Can you remove the "cmd /k" line from the end of the script? This should allow cmd to close after the script has run.

**Comment by stansu** [comment]
No, it still remain opened.

**Comment by DeclanRussell** [comment]
Ok I'm seeing other similar reports all on windows 7. The app was built on windows 10 so perhaps there is something specific I am missing to get it working on windows 7. I'll try and find some time soon to look into it.

**Comment by stansu** [comment]
Thanks for your time!

**Comment by DeclanRussell** [comment]
Sorry this took so long to resolve. It should be fixed in the latest version (see #13 for details). Feel free to reopen this issue if its still a problem.
