### ISSUE TITLE
"unknown exception"

### ISSUE THREAD

**Issue by ChristopheMoreau** [DeclanRussell/NvidiaAIDenoiser#14]
I, and thanks a lot for your awesome tool!

I'm wondering if you already had this error on a K2000 or K2100M nvidia's gpu? (with latest Quadro Drivers) Actually it doesn't work at all on those Graphic Cards. Do you know why?

Thanks a lot.

**Comment by Kikefluk** [comment]
I, and thanks a lot for your awesome tool!

I'm wondering if you already had this error on a K2000 or K2100M nvidia's gpu? (with latest Quadro Drivers) Actually it doesn't work at all on those Graphic Cards. Do you know why?

Thanks a lot.

**Comment by DeclanRussell** [comment]
Np glad you like it. Unfortunately the denoiser will only work on Nvidia GPUs of Maxwell architecture or higher. The K2000 and K2100M are both Kepler based, so they are too old. If this is a blocker for you, feel free to try out Intels CPU AI denoiser https://github.com/DeclanRussell/IntelOIDenoiser.
