### ISSUE TITLE
[OptiX]: Failed to load OptiX library 

### ISSUE THREAD

**Issue by Iron-Stark** [DeclanRussell/NvidiaAIDenoiser#15]
I installed the windows binary and ran the denoiser.exe with the input image. I am getting the error message [OptiX]: Failed to load OptiX library. I have a Nvidia Quadro P2000 and I have the latest version of drivers installed on my laptop. I also installed OptiX 6.5 from nvidia's website but that did not fix the issue. Any pointers on what I can do to fix this?

**Comment by DeclanRussell** [comment]
Hey @Iron-Stark 
Sorry for the slow reply, I was on holiday :) Can you send your driver version? Checking on the nvidia driver website it looks like the latest driver is from the 430 branch, which although is newer, is an older version of the driver. Try the one called,
```
| Quadro Desktop/Quadro Notebook Driver Release 435 QNF | R435 U2 (436.30) | September 10, 2019 |
```

**Comment by Iron-Stark** [comment]
Thanks for your response. I'll try that.
