### ISSUE TITLE
Improve Project Build And Config

### ISSUE THREAD

**Issue by Bit00009** [DeclanRussell/NvidiaAIDenoiser#19]
tbh, this is the worst project i've ever seen in my life
so messy everything is wrong and misnamed 
please upload a clean version to work with Visual Studio

**Comment by DeclanRussell** [comment]
@Bit00009 if you don't like it, don't use it. Better yet, if you think you can do better, feel free to contribute to the project with a PR. Then you can fix all the issues yourself instead of just complaining. I have no obligations to this project, and your snide comments will get you nowhere.
