### ISSUE TITLE
Is there any CPU based decoder available? 

### ISSUE THREAD

**Issue by rt258** [DeclanRussell/NvidiaAIDenoiser#3]
Since I am working with CPU render, wondering is there any CPU based decoder available?

Best,
RT

**Comment by DeclanRussell** [comment]
Hey,
So this implementation is unfortunately GPU only. There is no reason this algorithm couldn't be ported to the CPU (see the paper here http://research.nvidia.com/publication/interactive-reconstruction-monte-carlo-image-sequences-using-recurrent-denoising) but I think its unlikely I will have the time or the resources to make a train such a thing any time soon.

For a CPU denoiser I would happily recommend "Noice" the Arnold denoiser which is currently free to use. This denoiser is CPU based and is also temporally stable. However it is based on different algorithms to this AI denoiser.

Cheers,
Dec

**Comment by rt258** [comment]
Dear Dec,
Arnold is indeed a good idea worth to try! Thanks for the suggestion! 

Best,
RT
