### ISSUE TITLE
Retraining network

### ISSUE THREAD

**Issue by jaisonoh** [DeclanRussell/NvidiaAIDenoiser#5]
Hi, there.

I want to train the network with custom dataset. Is there any way to train again?

Thanks.

**Comment by Meetem** [comment]
No you can’t. Trained model owned and trained by nvidia, so they only
provide functions to use NN as is.

чт, 2 авг. 2018 г. в 5:39, jaisonoh <notifications@github.com>:

**Comment by DeclanRussell** [comment]
Actually yes you can, heres is a snippet from the OptiX programming guide:

> You can also create a custom model by training the denoiser with your own set of images and use the resulting training data in OptiX, but this process is not part of OptiX itself. To learn how to generate your own training data based on your renderer's images you can attend the course Rendered Image Denoising using Autoencoders, which is part of the NVIDIA Deep Learning Institute.

I haven't met anyone yet who has actually managed to create there own training data set yet as it is a very demanding process which requires having a few thousand image pairs (I think nvidia used 20,000). If anyone is seriously interested creating their own training data set I would be happy to add support for it in this application.

**Comment by jaisonoh** [comment]
Thanks for your answer.
I'll try the course.
