### ISSUE TITLE
I Found more missing .dlls

### ISSUE THREAD

**Issue by Cypencil** [DeclanRussell/NvidiaAIDenoiser#7]
Hello, sir,
I'm trying to launch your denoiser, but my computer tells me that the following dlls are missing:
libmmd.dll
half.dll
tbb.dll
sysntfy.dll
gpsvc.dll
openimageio.dll
iex.dll
ilmimf.dll
ilmthread.dll
ieshims.dll
msvcr80.dll
msvcp80.dll
zlib1.dll
I am sure that I've installed VC++ 2005, 2008, 2010, 2012, 2013, 2017, but still miss these dlls, could you tell me what runtime library has not installed?

**Comment by DeclanRussell** [comment]
Hey,
All the dlls that are required should be in the package you downloaded and you shouldn't need to install anything. Have you moved the Denoiser.exe out of the folder you downloaded?

**Comment by Cypencil** [comment]
Yeah, it still show me that message, and if I move all the dlls into the same directory of the exe, it will crash down soon after launch.

**Comment by DeclanRussell** [comment]
Could you try redownloading the package, extracting and then trying the denoiser without moving it anywhere? If it still crashes, one possible cause could be that you need to update your Nvidia driver. the denoiser requires at least version 390 or higher.

**Comment by Cypencil** [comment]
All right, I did that, redownloading, extracting, not moving any file, and my Nvidia driver has been updated to 398, but it still fails to locate those dlls. If I move dlls, it will still crash down.

**Comment by DeclanRussell** [comment]
Hmmm, that fact that you need to move any dlls is strange. The Denoiser.exe should look in the relative directory for the dlls, which is where they are in the package.

As for the crash can you give me any more information on how you are using it? What command line arguments are you using? What image format?

**Comment by Cypencil** [comment]
I feel strange, too. The Dependency Walker also shows that some of the dlls are not found, so I have to move them. The crash happens too fast that the cmd window disappears as soon as I see it, so I have no choice to operate it.

When I start the Denoiser.exe for the first time after I turn on my computer, it displays:
    "Launching Nvidia AI Denoiser command line app v2.0
     Created by Declan Russell <25/12/2017 ~ Merry Christmas!>
     No input image could be loaded"
in less than 1s then crashes. And if I start it again it displays nothing and crashes.

**Comment by Meetem** [comment]
Looks like there is time for debugging. Can you build and run app with
visual studio? (You’ll also need to install CUDA)

вс, 12 авг. 2018 г. в 13:15, 10572578 <notifications@github.com>:

**Comment by DeclanRussell** [comment]
How are you launching the denoiser? Are you just clicking on the exe? Its a command line tool so you will need to run it with cmd. If you haven't used command line tools here is a crash course in how to use it.

1. Launch cmd
2. Enter this into the command line
C:/Location of denoiser/Denoiser.exe -i C:/Location of image to be denoised/noiseyImage.jpg -o C:/Location to save image/denoisedImage.jpg
3. Hit enter
4. You should see something similar to the following written by cmd

Launching Nvidia AI Denoiser command line app v2.0
Created by Declan Russell (25/12/2017 ~ Merry Christmas!)
Input image: C:/Location of image to be denoised/noiseyImage.jpg
Loaded successfully
Output image: C:/Location to save image/denoisedImage.jpg
Denoising…
Denoising complete
Saving to: C:/Location to save image/denoisedImage.jpg
Done!

5. Hopefully everything has worked out and you have some nice noise free images

**Comment by Cypencil** [comment]
Oh, I made it in this way... I'm sorry for my lack of common sense. And I really thank you for your patience!

**Comment by DeclanRussell** [comment]
Great glad to hear you got it working. It was no problem :)
