### ISSUE TITLE
Denoised image isn' t much better than input

### ISSUE THREAD

**Issue by obrotowy** [DeclanRussell/NvidiaAIDenoiser#9]
Hello.
Recently, I wanted to try this AI but the result was... really bad.
I took a shot on my Sony A99 II with very high ISO, convert it from RAW to JPG inside Photoshop and then put it into this AI. 

## Input
![input](https://user-images.githubusercontent.com/26191968/49701250-43032a00-fbea-11e8-886c-782fab476aa7.jpg)

## Output
![denoised](https://user-images.githubusercontent.com/26191968/49701299-f9670f00-fbea-11e8-8c25-9f92effd0135.jpg)

### Specs
Ryzen 7 2700X
MSI X470 Gaming Pro
2x16GB G.Skill Ripjaws V 3000MHz CL15
GTX 970 4GB (Driver version: 416.34)

### Used command
```denoiser.exe -i raw.jpg -o denoised.jpg -hdr 0```
switching hdr to 1 didn' t change anything

**Comment by ultra-sonic** [comment]
I have to disappoint you mate, but this denoiser ONLY works on computer generated (read rendered) images. It has NO IDEA what to do with noise from an image-sensor.

**Comment by DeclanRussell** [comment]
I have done some similar tests with the denoiser and photos with similar results. It seems that it is not very good at denoising spectral noise. I did have some success with monochrome photos. This is likely due to the renderer that the training data was generated with also producing monochrome noise in the renders.

**Comment by obrotowy** [comment]
Oh :(
Is there any cool AI Algorithm to remove noise and scratches (from old photos shot on analog camera) to use instead?

**Comment by RyanOY** [comment]
If you highlight the noise in a real picture by sharping it, you can get a denoised picture out of this ai denoiser. Here are the samples: https://photos.app.goo.gl/L8tydgmijZWgxUMN8

**Comment by obrotowy** [comment]
Yes, but it makes output very very soft. Nvm, I'll use Topaz Denoise or AI Clear instead of this :(
